-- π搭子真实数据版数据库结构
-- 用新的 real_* 表，避免影响当前 paidazi.cn 演示版使用的旧表。

create extension if not exists pgcrypto;

create table if not exists real_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text,
  nickname text not null default 'π星人',
  avatar text not null default 'https://randomuser.me/api/portraits/lego/1.jpg',
  tags jsonb not null default '{}',
  personality_answers jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table real_profiles add column if not exists email text;

create table if not exists real_community_posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  category_name text not null,
  title text not null default '',
  content text not null,
  contact text not null default '',
  nickname text not null,
  avatar text not null,
  likes integer not null default 0,
  comments_count integer not null default 0,
  url text,
  link_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists real_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid not null references real_community_posts(id) on delete cascade,
  parent_id bigint references real_comments(id) on delete cascade,
  nickname text not null,
  avatar text not null,
  content text not null,
  to_nickname text,
  created_at timestamptz not null default now()
);

create table if not exists real_demands (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  category_name text not null,
  title text not null default '',
  contact text not null default '',
  nickname text not null,
  avatar text not null,
  tags text[] not null default '{}',
  personality_answers jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists real_invites (
  id bigint generated by default as identity primary key,
  from_user_id uuid not null references auth.users(id) on delete cascade,
  from_nickname text not null,
  to_user_id uuid references auth.users(id) on delete set null,
  to_user text not null,
  demand_id bigint references real_demands(id) on delete cascade,
  status text not null default 'pending',
  content text not null default '邀请你一起学习',
  created_at timestamptz not null default now()
);

create table if not exists real_bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid not null references real_community_posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, post_id)
);

create table if not exists real_post_likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid not null references real_community_posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, post_id)
);

alter table real_profiles enable row level security;
alter table real_community_posts enable row level security;
alter table real_comments enable row level security;
alter table real_demands enable row level security;
alter table real_invites enable row level security;
alter table real_bookmarks enable row level security;
alter table real_post_likes enable row level security;

drop policy if exists "profiles select own" on real_profiles;
drop policy if exists "profiles insert own" on real_profiles;
drop policy if exists "profiles update own" on real_profiles;
create policy "profiles select own" on real_profiles for select to authenticated using (auth.uid() = id);
create policy "profiles insert own" on real_profiles for insert to authenticated with check (auth.uid() = id);
create policy "profiles update own" on real_profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "posts select signed in" on real_community_posts;
drop policy if exists "posts insert own" on real_community_posts;
drop policy if exists "posts update own" on real_community_posts;
drop policy if exists "posts delete own" on real_community_posts;
create policy "posts select signed in" on real_community_posts for select to authenticated using (true);
create policy "posts insert own" on real_community_posts for insert to authenticated with check (auth.uid() = user_id);
create policy "posts update own" on real_community_posts for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "posts delete own" on real_community_posts for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "comments select signed in" on real_comments;
drop policy if exists "comments insert own" on real_comments;
drop policy if exists "comments delete own" on real_comments;
create policy "comments select signed in" on real_comments for select to authenticated using (true);
create policy "comments insert own" on real_comments for insert to authenticated with check (auth.uid() = user_id);
create policy "comments delete own" on real_comments for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "demands select signed in" on real_demands;
drop policy if exists "demands insert own" on real_demands;
drop policy if exists "demands update own" on real_demands;
drop policy if exists "demands delete own" on real_demands;
create policy "demands select signed in" on real_demands for select to authenticated using (true);
create policy "demands insert own" on real_demands for insert to authenticated with check (auth.uid() = user_id);
create policy "demands update own" on real_demands for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "demands delete own" on real_demands for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "invites select own" on real_invites;
drop policy if exists "invites insert own" on real_invites;
drop policy if exists "invites update own" on real_invites;
create policy "invites select own" on real_invites for select to authenticated using (auth.uid() = from_user_id or auth.uid() = to_user_id);
create policy "invites insert own" on real_invites for insert to authenticated with check (auth.uid() = from_user_id);
create policy "invites update own" on real_invites for update to authenticated using (auth.uid() = from_user_id or auth.uid() = to_user_id);

drop policy if exists "bookmarks select own" on real_bookmarks;
drop policy if exists "bookmarks insert own" on real_bookmarks;
drop policy if exists "bookmarks delete own" on real_bookmarks;
create policy "bookmarks select own" on real_bookmarks for select to authenticated using (auth.uid() = user_id);
create policy "bookmarks insert own" on real_bookmarks for insert to authenticated with check (auth.uid() = user_id);
create policy "bookmarks delete own" on real_bookmarks for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "likes select signed in" on real_post_likes;
drop policy if exists "likes insert own" on real_post_likes;
create policy "likes select signed in" on real_post_likes for select to authenticated using (true);
create policy "likes insert own" on real_post_likes for insert to authenticated with check (auth.uid() = user_id);

create or replace function real_like_post(target_post_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_likes integer;
begin
  insert into real_post_likes(user_id, post_id)
  values (auth.uid(), target_post_id)
  on conflict do nothing;

  update real_community_posts
  set likes = (
    select count(*)::integer from real_post_likes where post_id = target_post_id
  )
  where id = target_post_id
  returning likes into next_likes;

  return coalesce(next_likes, 0);
end;
$$;

create or replace function real_increment_comments_count(target_post_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  update real_community_posts
  set comments_count = (
    select count(*)::integer from real_comments where post_id = target_post_id
  )
  where id = target_post_id
  returning comments_count into next_count;

  return coalesce(next_count, 0);
end;
$$;

create index if not exists idx_real_posts_created_at on real_community_posts(created_at desc);
create index if not exists idx_real_posts_category on real_community_posts(category);
create index if not exists idx_real_comments_post_id on real_comments(post_id);
create index if not exists idx_real_comments_parent_id on real_comments(parent_id);
create index if not exists idx_real_demands_created_at on real_demands(created_at desc);
create index if not exists idx_real_demands_category on real_demands(category);
create index if not exists idx_real_invites_from_user on real_invites(from_user_id);
create index if not exists idx_real_invites_to_user on real_invites(to_user_id);
create index if not exists idx_real_bookmarks_user on real_bookmarks(user_id);

-- 免登录小范围测试版：允许访客直接读取、发布、评论、点赞。
alter table real_community_posts add column if not exists guest_id text;
alter table real_comments add column if not exists guest_id text;
alter table real_demands add column if not exists guest_id text;
alter table real_invites add column if not exists from_guest_id text;

alter table real_community_posts alter column user_id drop not null;
alter table real_comments alter column user_id drop not null;
alter table real_demands alter column user_id drop not null;
alter table real_invites alter column from_user_id drop not null;

drop policy if exists "posts select public" on real_community_posts;
drop policy if exists "posts insert public" on real_community_posts;
create policy "posts select public" on real_community_posts for select to anon, authenticated using (true);
create policy "posts insert public" on real_community_posts for insert to anon, authenticated with check (true);

drop policy if exists "comments select public" on real_comments;
drop policy if exists "comments insert public" on real_comments;
create policy "comments select public" on real_comments for select to anon, authenticated using (true);
create policy "comments insert public" on real_comments for insert to anon, authenticated with check (true);

drop policy if exists "demands select public" on real_demands;
drop policy if exists "demands insert public" on real_demands;
create policy "demands select public" on real_demands for select to anon, authenticated using (true);
create policy "demands insert public" on real_demands for insert to anon, authenticated with check (true);

drop policy if exists "invites select public" on real_invites;
drop policy if exists "invites insert public" on real_invites;
create policy "invites select public" on real_invites for select to anon, authenticated using (true);
create policy "invites insert public" on real_invites for insert to anon, authenticated with check (true);

create or replace function real_guest_like_post(target_post_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_likes integer;
begin
  update real_community_posts
  set likes = coalesce(likes, 0) + 1
  where id = target_post_id
  returning likes into next_likes;

  return coalesce(next_likes, 0);
end;
$$;

create index if not exists idx_real_posts_guest_id on real_community_posts(guest_id);
create index if not exists idx_real_comments_guest_id on real_comments(guest_id);
create index if not exists idx_real_demands_guest_id on real_demands(guest_id);
create index if not exists idx_real_invites_from_guest on real_invites(from_guest_id);
